// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: auth_queries.sql

package database

import (
	"context"
)

const getForApiKey = `-- name: GetForApiKey :one
SELECT 
    id,
    email,
    name,
    api_key,
    created_at,
    updated_at
FROM users
WHERE api_key = $1
`

func (q *Queries) GetForApiKey(ctx context.Context, apiKey []byte) (User, error) {
	row := q.db.QueryRowContext(ctx, getForApiKey, apiKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
