// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: geolocation_queries.sql

package database

import (
	"context"
	"time"
)

const createNewGeoLocation = `-- name: CreateNewGeoLocation :one
INSERT INTO geolocations (county, sub_county, location, sub_location)
VALUES ($1, $2, $3, $4)
RETURNING id, created_at
`

type CreateNewGeoLocationParams struct {
	County      string
	SubCounty   string
	Location    string
	SubLocation string
}

type CreateNewGeoLocationRow struct {
	ID        int32
	CreatedAt time.Time
}

func (q *Queries) CreateNewGeoLocation(ctx context.Context, arg CreateNewGeoLocationParams) (CreateNewGeoLocationRow, error) {
	row := q.db.QueryRowContext(ctx, createNewGeoLocation,
		arg.County,
		arg.SubCounty,
		arg.Location,
		arg.SubLocation,
	)
	var i CreateNewGeoLocationRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
