// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: household_queries.sql

package database

import (
	"context"
	"time"
)

const createNewHousehold = `-- name: CreateNewHousehold :one
INSERT INTO households (program_id, geolocation_id, name) 
VALUES ($1, $2, $3) 
RETURNING id, created_at
`

type CreateNewHouseholdParams struct {
	ProgramID     int32
	GeolocationID int32
	Name          string
}

type CreateNewHouseholdRow struct {
	ID        int32
	CreatedAt time.Time
}

func (q *Queries) CreateNewHousehold(ctx context.Context, arg CreateNewHouseholdParams) (CreateNewHouseholdRow, error) {
	row := q.db.QueryRowContext(ctx, createNewHousehold, arg.ProgramID, arg.GeolocationID, arg.Name)
	var i CreateNewHouseholdRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
