// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Program struct {
	ID          int32
	Name        sql.NullString
	Category    string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
