// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type Geolocation struct {
	ID          int32
	County      string
	SubCounty   string
	Location    string
	SubLocation string
	CreatedAt   time.Time
}

type Program struct {
	ID          int32
	Name        string
	Category    string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
