// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: program_queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createNewProgram = `-- name: CreateNewProgram :one
INSERT INTO programs (name, category, description) 
VALUES ($1, $2, $3) 
RETURNING id, created_at, updated_at
`

type CreateNewProgramParams struct {
	Name        sql.NullString
	Category    string
	Description string
}

type CreateNewProgramRow struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateNewProgram(ctx context.Context, arg CreateNewProgramParams) (CreateNewProgramRow, error) {
	row := q.db.QueryRowContext(ctx, createNewProgram, arg.Name, arg.Category, arg.Description)
	var i CreateNewProgramRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
